version: "3.5"
services:
    postgres:
        container_name: postgres
        image: postgres:13.3-alpine
        restart: always
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_USER: "developer"
            POSTGRES_PASSWORD: "supersecretpassword"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks: 
            - backend
    adminer:
        container_name: adminer
        image: adminer:4.8.1-standalone
        restart: always
        ports:
            - "8090:8080"
        depends_on: 
            - postgres
        networks: 
            - backend
    redis:
        container_name: redis
        image: redis:6.2.4-alpine
        restart: always
        ports:
            - "6379:6379"
        networks: 
            - backend
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        networks: 
            - backend
    localstack:
        container_name: localstack
        image: localstack/localstack:latest
        environment: 
            - AWS_DEFAULT_REGION=ap-southeast-1
            - EDGE_PORT=4566
            - SERVICES=s3
        ports: 
            - '4566-4583:4566-4583'
        volumes: 
            - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
            
volumes:
    postgres-data:
        name: postgres-data

networks:
    backend:
        name: backend-network